version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Priyajit@2002
      POSTGRES_DB: CSV_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: priyajitadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: priyajitgantayat2002@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  app:
    build:
      context: .
    container_name: golang-app
    depends_on:
      - postgres
    command: ["main"]
    volumes:
      - .:/app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: priyajitdb
      DB_PASSWORD: priyajit@123
      DB_NAME: CSV_db

volumes:
  postgres-data: